---
commitizen:
  allowed_prefixes:
  - Merge
  - Revert
  - Pull request
  - fixup!
  - squash!
  - amend!
  - 'bump:'
  bump_message: 'bump: image $current_version -> $new_version'
  major_version_zero: true
  name: wyld_cz
  tag_format: image-$version
  update_changelog_on_bump: false
  version: 0.0.0
  version_provider: commitizen
  version_scheme: semver
