---
commitizen:
  allowed_prefixes:
  - Merge
  - Revert
  - Pull request
  - fixup!
  - squash!
  - amend!
  - 'bump:'
  bump_message: 'bump: image $current_version -> $new_version'
  changelog_file: CHANGELOG.md
  changelog_paths:
  - packer
  major_version_zero: true
  name: wyld_cz
  tag_format: image-$version
  update_changelog_on_bump: true
  version: 0.2.1
  version_provider: commitizen
  version_scheme: semver
