variable "alpine_branch" {
  type = string
}

variable "alpine_version" {
  type = string
}

variable "iso_checksum" {
  type = string
}

variable "disk_size" {
  type        = string
  default     = "1G"
  description = "Virtual disk size; derived images grow from this."
}

variable "memory" {
  type        = number
  default     = 2048
  description = "Guest RAM in MB during the build only."
}

variable "cpus" {
  type    = number
  default = 2
}

variable "build_password" {
  type        = string
  sensitive   = true
  description = "Root password while packer builds; generated by the Makefile per build, locked in the agents image."
}
