variable "version" {
  type        = string
  default     = "0.0.0-dev"
  description = "Image version, the part of the packer_<version> tag after the prefix."
}

variable "alpine_branch" {
  type        = string
  default     = "v3.24"
  description = "Alpine stable branch the ISO is downloaded from."
}

variable "alpine_version" {
  type        = string
  default     = "3.24.1"
  description = "Alpine point release the base image is built from."
}

variable "iso_checksum" {
  type        = string
  default     = "sha256:e73a6241bd5f3c5c2d4d38c02cc52c378c0415a7c888bd292066bf36e0f41a39"
  description = "Checksum of alpine-virt-<version>-x86_64.iso, from latest-releases.yaml."
}

variable "image_name" {
  type    = string
  default = "naos-base"
}

variable "output_directory" {
  type    = string
  default = "build/base"
}

variable "disk_size" {
  type        = string
  default     = "4G"
  description = "Virtual disk size; derived images grow from this."
}

variable "memory" {
  type        = number
  default     = 2048
  description = "Guest RAM in MB during the build only."
}

variable "cpus" {
  type    = number
  default = 2
}

variable "accelerator" {
  type    = string
  default = "kvm"
}

variable "headless" {
  type    = bool
  default = true
}

variable "build_password" {
  type        = string
  sensitive   = true
  description = "Root password while packer builds; generated by the Makefile, locked in the agents image."
}
